import type { LocationDefinition } from "../../game/types";

export const locationDefinitions: Record<string, LocationDefinition> = {
  asteria: {
    id: "asteria",
    name: "Asteria",
    level: "planet",
    type: "planet",
    dangerLevel: 0,
    childLocationIds: ["valoria_continent"],
    connectedLocations: [],
    npcIds: [],
    eventPoolIds: ["world_rumors"],
  },
  valoria_continent: {
    id: "valoria_continent",
    name: "Valoria",
    level: "continent",
    type: "continent",
    dangerLevel: 1,
    parentLocationId: "asteria",
    childLocationIds: ["elyndor_kingdom"],
    connectedLocations: ["asteria"],
    npcIds: [],
    eventPoolIds: ["continent_events"],
  },
  elyndor_kingdom: {
    id: "elyndor_kingdom",
    name: "Reino de Elyndor",
    level: "country",
    type: "country",
    dangerLevel: 1,
    parentLocationId: "valoria_continent",
    childLocationIds: ["laren_state"],
    connectedLocations: ["valoria_continent"],
    npcIds: [],
    eventPoolIds: ["kingdom_news"],
  },
  laren_state: {
    id: "laren_state",
    name: "Marca de Laren",
    level: "state",
    type: "state",
    dangerLevel: 1,
    parentLocationId: "elyndor_kingdom",
    childLocationIds: ["elaria_city"],
    connectedLocations: ["elyndor_kingdom"],
    npcIds: [],
    eventPoolIds: ["state_patrols"],
  },
  elaria_city: {
    id: "elaria_city",
    name: "Elaria",
    level: "city",
    type: "village",
    dangerLevel: 1,
    dangerByTime: {
      evening: 1,
      night: 2,
      late_night: 3,
    },
    parentLocationId: "laren_state",
    childLocationIds: ["first_village", "guild_hall", "shadow_woods"],
    connectedLocations: ["laren_state"],
    npcIds: ["hooded_mentor", "village_blacksmith", "guild_clerk", "night_informant"],
    eventPoolIds: ["village_day", "village_night"],
  },
  first_village: {
    id: "first_village",
    name: "Praca de Elaria",
    level: "locality",
    type: "district",
    dangerLevel: 1,
    dangerByTime: {
      evening: 1,
      night: 2,
      late_night: 3,
    },
    parentLocationId: "elaria_city",
    childLocationIds: [],
    connectedLocations: ["guild_hall", "shadow_woods", "elaria_city"],
    npcIds: ["hooded_mentor", "village_blacksmith", "night_informant"],
    eventPoolIds: ["village_day", "village_night"],
  },
  guild_hall: {
    id: "guild_hall",
    name: "Guilda de Elaria",
    level: "locality",
    type: "district",
    dangerLevel: 0,
    parentLocationId: "elaria_city",
    childLocationIds: [],
    connectedLocations: ["first_village", "elaria_city"],
    npcIds: ["guild_clerk", "hooded_mentor"],
    eventPoolIds: ["guild_jobs"],
  },
  shadow_woods: {
    id: "shadow_woods",
    name: "Bosque Sombrio",
    level: "locality",
    type: "forest",
    dangerLevel: 3,
    dangerByTime: {
      evening: 2,
      night: 4,
      late_night: 5,
    },
    parentLocationId: "elaria_city",
    childLocationIds: [],
    connectedLocations: ["first_village", "elaria_city"],
    npcIds: [],
    eventPoolIds: ["forest_common", "forest_night"],
  },
};

